image: maven:3.8-openjdk-18

variables:
  CI_DEBUG_SERVICES: "true"

services:
  - name: mongo:latest
    alias: mongointegration

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"

test-job-JUnit:
  stage: test
  script:
    - echo "This job tests JUnit"
    - "echo 'Running JUnitTest for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.controllerTest.*Test' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.modelTest.*Test' test"

test-job-Integration:
  stage: test

  variables:
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "example"

  script:
    - "echo 'Running Integration tests for all packages'"
    - "mvn -Dtest=de.hdm.se3project.backend.controller.integrationTest.repositoryTest.AccountRepositoryTest test"
