image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

services:
  - name: docker:dind #docker in docker
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" ]

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # Instruct Testcontainers to use the daemon of DinD, use port 2735 for non-tls connections.
  #DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS - Transport Layer Security.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"
    - "mvn compile"
  rules:
    - changes:
      - 'src/**/*'

test-job-JUnit:
  stage: test
  script:
    - echo "This job tests something"
    - "echo 'Running JUnitTest for packages'"
    #- "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.controllerTest.*Test' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.modelTest.*Test' test"

test-job-Integration:
  stage: test
  script:
    - echo "This job tests something"
    - "echo 'Running Integration for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.integrationTest.*.*Test' test"