cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3-openjdk-17
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"
    - "mvn compile"

unit-tests:
  stage: test
  image: maven:3-openjdk-17
  script:
    - echo "This job tests JUnit"
    - "echo 'Running JUnitTest for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.jUnitTest.controllerTest.*mvn clean install -DskipTests'"

integration-tests:
  stage: test
  variables:
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "dummy"
    #SPRING_DATA_MONGODB_URI: "mongodb://root:dummy@mongo"
    #CI_DEBUG_SERVICES: "true"
  #mongo image is used only here
  services:
    - name: mongo:4.4
  image: maven:3-openjdk-17
  script:
    - echo "This job tests Integration Tests"
    - "echo 'Running Integration tests for all packages'"
    - "mvn -Dtest=de.hdm.se3project.backend.integrationTest.repositoryTest.*Test test"
    - "mvn -Dtest=de.hdm.se3project.backend.integrationTest.servicesTest.*Test test"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

