stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3.8-openjdk-18
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"

test-job-JUnit:
  stage: test
  image: maven:3.8-openjdk-18
  script:
    - echo "This job tests JUnit"
    - "echo 'Running JUnitTest for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.controllerTest.*Test' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.modelTest.*Test' test"