cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3-openjdk-17
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"
    - "mvn compile"

test-job-JUnit:
  stage: test
  image: maven:3-openjdk-17
  script:
    - echo "This job tests something"
    - "echo 'Running JUnitTest for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.controllerTest.*Test' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.jUnitTest.modelTest.*Test' test"

test-job-Integration:
  stage: test
  image: maven:3-openjdk-17
  script:
    - echo "This job tests something"
    - "echo 'Running Integration for packages'"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.integrationTest.repositoryTest.AccountRepositoryTest' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.integrationTest.repositoryTest.FridgeItemRepositoryTest' test"
    - "mvn '-Dtest=de.hdm.se3project.backend.controller.integrationTest.repositoryTest.RecipeRepositoryTest' test"
