cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3-openjdk-17
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"
    - "mvn compile"

test-job1:
  stage: test
  image: maven:3-openjdk-17
  script:
    - echo "This job tests something"
    - "echo 'Starting Test Stage'"
    - "mvn -Dtest=AccountControllerTest test"
