cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test
  - package

build-job:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - "echo 'Starting Build Stage'"
    - "mvn compile"

test-job1:
  stage: test
  image: maven:3.6.3-openjdk-17
  script:
    - echo "This job tests something"
    - "echo 'Starting Test Stage'"
    - "mvn -Dtest=AccountControllerTest test"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

test-job2:
  stage: test
  image: maven:3.6.3-openjdk-17
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
